### ISSUE TITLE
Container error

### ISSUE THREAD

**Issue by wm-simon** [riasvdv/statamic-button-box#5]
Hey,

because of the other issue #4, I've added the settings to the blueprint file directly.
The field is shown now, but when I add an image, this error is shown:
```
Assets fieldtype is missing the "container" option.
Since you have multiple asset containers, you need to specify which one should be used in the field.
```
```
            -
              handle: choice
              field:
                type: button_box
                display: Choice
                options:
                  -
                    label: Left
                    value: left
                    image: null
                    icon: null
                  -
                    label: Center
                    value: center
                    image: null
                    icon: null
                  -
                    label: Right
                    value: right
                    image: /img/grafiken/icons/layout-1.svg
                    icon: null
```
